server.port=8443
server.ssl.enabled=true
server.ssl.key-store=file:/etc/cas/thekeystore
server.ssl.key-store-password=changeit
server.ssl.key-password=changeit
server.ssl.key-alias=cas


cas.authn.accept.users=admin::password
cas.service-registry.core.init-from-json=true
cas.service-registry.json.location=/etc/cas/services
cas.service-registry.core.init-default-services=false
cas.tgc.crypto.signing.key=rNZDqLsIFM8D51QxetOUBkwlMrkH1f9DDKOJxD8GJ1n4wfhCAw3vRsMA_mJZ6CS3W9oLPVvgnR0RjCShjdyREw