name: Build AsciiDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby (pour Asciidoctor)
        uses: ruby/setup-ruby@v1

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Convert AsciiDoc to HTML
        run: |
          asciidoctor docs/*.adoc -D docs/
